name: Run Code and Check Output

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  run-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run the code with input
        run: |
          python main.py < input.txt > output.txt

      - name: Check output against expected
        run: |
          diff output.txt expected_output.txt
